### ISSUE TITLE
Froggy esta hardcodeando todo :@

### ISSUE THREAD

**Issue by HectorBlisS** [Oswaldinho24k/agendaBackend#2]
ese wey me cae bien

**Comment by FoggyRocket** [comment]
la veda es que OSwa no revisa

**Comment by BrendaOrtega** [comment]
Deshonra, desgracia...

**Comment by Oswaldinho24k** [comment]
La verda e que no me avisas

**Comment by HectorBlisS** [comment]
Ya salio el peine!: 7ce77a88b5c91ed861a441b2e766b7a39ca37cce

**Comment by Oswaldinho24k** [comment]
ya se supo

**Comment by HectorBlisS** [comment]
a256d40173311dfd9541cdcf2b642ff2e2ce800f
